hospital/urls.py
from django.urls import path
from . import views

app_name='hospital'
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("patient-registration/", views.patient_registration, name="add_patient"),
    path("patient-information/", views.patient_information, name="patient_info"),
    path("patient-log/", views.patient_log, name="patient_log")
]

hospital_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("hospital.urls")),
    path('admin/', admin.site.urls),
]

hospital/models.py
from django.db import models

import datetime
from django.utils import timezone

class Department(models.Model):
    dept_type = models.CharField(max_length=64)
    function = models.CharField(max_length=750)

    def __str__(self):
        return f"{self.dept_type}"
    

class Specialization(models.Model):
    type = models.CharField(max_length=64)
    role = models.CharField(max_length=750)

    def __str__(self):
        return f"{self.type}"
    

class Doctor(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(max_length=254, unique=True)
    specialty = models.ForeignKey(Specialization, on_delete=models.CASCADE, related_name="experts")
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name="departments")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    

class Nurse(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(max_length=254, unique=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name="wards")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    

class Patient(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    contact = models.CharField(max_length=30)
    residential_address = models.CharField(max_length=550)
    gender = models.CharField(max_length=2)
    date_of_birth = models.DateField()

    # validate date of birth
    def valid_date_of_birth(self):
        now = timezone.now().date()
        return self.date_of_birth <= now

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    

class Patient_Record(models.Model):
    PERIOD_ADMITTED = [
        ('morning', 'Morning'),
        ('afternoon', 'Afternoon'),
        ('evening', 'Evening'),
        ('night', 'Night')
    ]
    check_in_date = models.DateField()
    check_in_period = models.CharField(max_length=64, choices=PERIOD_ADMITTED)
    check_out_date = models.DateField(blank=True, null=True)
    check_out_period = models.CharField(max_length=64, blank=True, choices=PERIOD_ADMITTED)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name="patients")
    assigned_doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name="doctors")

    def valid_checkin_date(self):
        now = timezone.now().date()
        return self.check_in_date <= now

    def __str__(self):
        return f"{self.patient}"
    

hospital/forms.py
from django import forms
from .models import Patient_Record
from django.contrib.admin import widgets

CHOICES = [ 
    ('M','Male'), 
    ('F', 'Female'), 
    ]

class DateInput(forms.DateInput):
    input_type = 'date'

    
class RegisterForm(forms.Form):
    first_name = forms.CharField(
                widget=forms.TextInput(attrs={'class':'form-control'}), 
                required=True
                )
    last_name = forms.CharField(
                widget=forms.TextInput(attrs={'class':'form-control'}), 
                required=True
                )
    gender = forms.ChoiceField(
                widget=forms.RadioSelect, choices=CHOICES, 
                required=True
                )
    contact = forms.CharField(
                widget=forms.NumberInput(attrs={'class':'form-control'}), 
                required=True
                )
    residential_address = forms.CharField(
                widget=forms.TextInput(attrs={'class':'form-control'}), 
                required=True
                )
    date_of_birth = forms.DateField(
                widget=DateInput(attrs={'class':'form-control'}), 
                required=True
                )


class PatientLogForm(forms.ModelForm):
    class Meta:
        model = Patient_Record
        fields = '__all__'
        widgets = {
            'check_in_date': DateInput(attrs={'class':'form-control'}),
            'check_in_period': forms.Select(attrs={'class':'form-control'}),
            'check_out_date': DateInput(attrs={'class':'form-control'}),
            'check_out_period': forms.Select(attrs={'class': 'form-control'}),
            'patient': forms.Select(attrs={'class':'form-control'}),
            'assigned_doctor': forms.Select(attrs={'class': 'form-control'}),
        }

hospital/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .forms import RegisterForm, PatientLogForm
from .models import Patient, Patient_Record


def index(request):
    if not request.user.is_authenticated:
        return render(request, "hospital/login.htm", {"message": None})
    context = {}
    return render(request, "hospital/index.htm", context)


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('hospital:index'))
        else:
            return render(request, "hospital/login.htm", {"message": "Invalid credentials"})
    else:
        return render(request, "hospital/login.htm",)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('hospital:login'))


def patient_registration(request):
    # check whether request is POST
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():  
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            gender = form.cleaned_data['gender']
            contact = form.cleaned_data['contact']
            residential_address = form.cleaned_data['residential_address']
            date_of_birth = form.cleaned_data['date_of_birth']
            
            # if form is valid, create patient
            patient = Patient.objects.create(
                first_name=first_name, last_name=last_name, gender=gender, contact=contact,
                residential_address=residential_address, date_of_birth=date_of_birth
            )
            return HttpResponseRedirect(reverse('hospital:patient_log'))
    else:
        form = RegisterForm()
    return render(request, "hospital/add_patient.htm", {'form':form})


def patient_log(request):
    if request.method == 'POST':
        form = PatientLogForm(request.POST)
        if form.is_valid():
            check_in_date=form.cleaned_data['check_in_date']
            check_in_period = form.cleaned_data['check_in_period']
            check_out_date=form.cleaned_data['check_out_date']
            check_out_period = form.cleaned_data['check_out_period']
            patient=form.cleaned_data['patient']
            assigned_doctor = form.cleaned_data['assigned_doctor']

            log = Patient_Record.objects.create(
                check_in_date=check_in_date, check_in_period=check_in_period, 
                check_out_date=check_out_date, check_out_period=check_out_period,
                patient=patient, assigned_doctor=assigned_doctor
            )
            return HttpResponseRedirect(reverse('hospital:index'))
    else:
        form = PatientLogForm()
    return render(request, "hospital/patient_log.htm", {'form': form})



def patient_information(request):
    context = {
        "patients": Patient.objects.all(),
    }
    return render(request, "hospital/patient_info.htm", context)
    

hospital/templates/hospital/add_patient.htm
{% extends "hospital/layout.htm" %}

{% block title %} register-patient {% endblock %}

{% block body %}
<div class="container">
    <form action="{% url 'hospital:add_patient' %}" method="post">
        {% csrf_token %}

        <div class="card border-primary shadow col-sm-10 col-md-6 mx-auto" style="margin: 8% 0;">
            <div class="card-body">
                <div class="h4 mt-3 font-weight-bold text-uppercase text-center border-bottom border-secondary">
                    Patient Bio-Data
                </div>
                <div class="form-group">
                    <label for="">First Name:</label>
                    {{ form.first_name }}
                </div>

                <div class="form-group">
                    <label for="">Last Name:</label>
                    {{ form.last_name }}
                </div>

                <div class="form-group">
                    <label for="">Gender:</label>
                    {{ form.gender }}
                </div>

                <div class="form-group">
                    <label for="">Contact:</label>
                    {{ form.contact }}
                </div>

                <div class="form-group">
                    <label for="">Residential Address:</label>
                    {{ form.residential_address }}
                </div>

                <div class="form-group">
                    <label for="">Date Of Birth:</label>
                    {{ form.date_of_birth }}
                </div>

                <div class="form-group">
                    <input type="submit" value="Register" class="btn btn-success col-4 float-right">
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

hospital/templates/hospital/index.htm
{% extends "hospital/layout.htm" %}
{% load static %}
{% block title %} Index page {% endblock %}

{% block body %}
    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'hospital/images/slide_10.jpg' %}" class="d-block w-100" alt="">
            </div>
            <div class="carousel-item">
                <img src="{% static 'hospital/images/slide_11.jpg' %}" class="d-block w-100" alt="">
            </div>
            <div class="carousel-item">
                <img src="{% static 'hospital/images/slide_12.jpg' %}" class="d-block w-100" alt="">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="container">
            <div class="row mb-4 mt-4 text-center">
            <a href="{% url 'hospital:patient_info' %}" class="">
                <div class="col-md-4 col-sm-12 mb-5 text-center">
                    <img src="{% static 'hospital/images/boss.png' %}" class="rounded-circle bg-primary img-fluid" alt="img-1" 
                    width="120" height="120">

                    <div class="h5 text-uppercase mt-2">Patient Information</div>
                    </a>
                </div>


                <div class="col-md-4 col-sm-12 mb-5 text-center">
                <a href="{% url 'hospital:add_patient' %}" class="">
                    <img src="{% static 'hospital/images/boss.png' %}" class="rounded-circle bg-primary img-fluid"
                        alt="img-1" width="120" height="120">
                    
                    <div class="h5 text-uppercase mt-2">Patient Registration</div>
                    </a>
                </div>


                <div class="col-md-4 col-sm-12 mb-5 text-center">
                <a href="{% url 'hospital:patient_log' %}" class="">
                    <img src="{% static 'hospital/images/boss.png' %}" class="rounded-circle bg-primary img-fluid"
                        alt="img-1" width="120" height="120">
                    
                    <div class="h5 text-uppercase mt-2">Patient Records</div>
                </a>
                </div>
            </div>


            <div class="row mb-4 mt-4 text-center">

                <div class="col-md-4 col-sm-12 mb-5 text-center">
                    <img src="{% static 'hospital/images/boss.png' %}" class="rounded-circle bg-primary img-fluid"
                        alt="img-1" width="120" height="120">
                </div>


                <div class="col-md-4 col-sm-12 mb-5 text-center">
                    <img src="{% static 'hospital/images/boss.png' %}" class="rounded-circle bg-primary img-fluid"
                        alt="img-1" width="120" height="120">
                </div>


                <div class="col-md-4 col-sm-12 mb-5 text-center">
                    <img src="{% static 'hospital/images/boss.png' %}" class="rounded-circle bg-primary img-fluid"
                        alt="img-1" width="120" height="120">
                </div>
            </div>
    </div>
{% endblock %}

hospital/templates/hospital/layout.htm
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.21/af-2.3.5/b-1.6.2/b-colvis-1.6.2/b-html5-1.6.2/b-print-1.6.2/cr-1.5.2/fc-3.3.1/kt-2.5.2/r-2.2.5/rg-1.1.2/rr-1.2.7/sp-1.1.1/sl-1.3.1/datatables.min.css"/>
<link rel="stylesheet" href="{% static 'hospital/css/main.css' %}">
<title>{% block title %} {% endblock %}</title>
</head>
<body>

    {% block navbar %}
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg fixed-top navbar-dark" style="background-color: #0e2c41;">
                <a class="navbar-brand font-weight-bold" href="#">
                    <img src="{% static 'hospital/images/slide_5.jpg' %}" alt="" width="40" height="40"
                        class="rounded-circle d-inline-block align-top">
                    ChristCare Medical Home
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto mr-5 pb-1 text-uppercase">
                        <li class="nav-item active mr-4">
                            <a class="nav-link" href="{% url 'hospital:index' %}">Home <span class="sr-only">(current)</span></a>
                        </li>

                        <li class="nav-item active mr-4">
                            <a class="nav-link" href="{% url 'hospital:logout' %}">Logout </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    {% endblock %}

    {% block body %} 
    
    {% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.21/af-2.3.5/b-1.6.2/b-colvis-1.6.2/b-html5-1.6.2/b-print-1.6.2/cr-1.5.2/fc-3.3.1/kt-2.5.2/r-2.2.5/rg-1.1.2/rr-1.2.7/sp-1.1.1/sl-1.3.1/datatables.min.js"></script>
<script>
    $(document).ready(function() {
        $('#patient_table').DataTable({
            dom: 'B<"clear">lfrtip',
            buttons: {
                name: 'primary',
                buttons: ['copy', 'csv', 'excel', 'pdf']
            }
        });
    });
</script>

</body>
</html>

hospital/templates/hospital/login.htm
{% extends "hospital/layout.htm" %}

{% block title %} login page {% endblock %}

{% block navbar %} {% endblock %}

{% block body %}

    <div class="container">
        <div class="row h-100">
            <div class="col-md-5 col-sm-7 mx-auto" style="top: 150px;">
            
                <div class="card border-success shadow">
                    <div class="col-10 mx-auto text-center">
                        <div class="h3 card-title mt-3 font-weight-bold border-bottom border-warning"> LOGIN </div>
                    </div>

                        {% if message %}
                            <div class="alert alert-danger col-10 mx-auto text-center"> {{ message }}</div>
                        {% endif %}
                    
                    <div class="card-body">
                        <form action="{% url 'hospital:login' %}" method="post">
                            {% csrf_token %}

                            <div class="form-group">
                                <label for="username" class="font-weight-bold">Username</label>
                                <input type="text" name="username" id="username" class="form-control" required>
                            </div>

                            <div class="form-group">
                                <label for="password" class="font-weight-bold">Password</label>
                                <input type="password" name="password" id="password" class="form-control" required>
                            </div>

                            <div class="form-group float-right">
                                <input class="btn btn-primary form-control pl-5 pr-5 font-weight-bold" type="submit" name="btn" value="Login">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

hospital/templates/hospital/patient_info.htm
{% extends "hospital/layout.htm" %}

{% block title %} Patients-Records {% endblock %}
{% block navbar %} {% endblock %}

{% block body %}
    <div class="container mt-5 mb-5">
        <div class="h4 text-center border-bottom text-uppercase font-weight-bold">Patients Records</div>
        <table id="patient_table" class="table table-striped table-bordered display" style="width:100%">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Contact</th>
                    <th>Residential Address</th>
                    <th>Gender</th>
                    <th>Date of birth</th>
                </tr>
            </thead>

            <tbody>
                {% for patient in patients %}
                <tr>
                    <td> {{ patient.first_name }} {{ patient.last_name }}  </td>
                    <td>{{ patient.contact }} </td>
                    <td>{{ patient.residential_address }} </td>
                    <td>{{ patient.gender }} </td>
                    <td>{{ patient.date_of_birth }} </td>
                </tr>
                {% empty %}
                    <div class="h4">There is No Patient Records</div>
                {% endfor %}
            </tbody>

            <tfoot>
                <tr>
                    <th>Name</th>
                    <th>Contact</th>
                    <th>Residential Address</th>
                    <th>Gender</th>
                    <th>Date of birth</th>
                </tr>
            </tfoot>
        </table> 
    </div>
{% endblock %}

hospital/templates/hospital/patient_log.htm
{% extends "hospital/layout.htm" %}

{% block title %} register-patient {% endblock %}

{% block body %}
<div class="container">
    <form action="{% url 'hospital:patient_log' %}" method="post">
        {% csrf_token %}

        <div class="card border-primary shadow col-sm-10 col-md-6 mx-auto" style="margin: 8% 0;">
            
            <div class="card-body">
                <div class="h4 mt-3 font-weight-bold text-uppercase text-center border-bottom border-secondary">
                    Patient Medical Details
                </div>
                <div class="form-group">
                    <label for="">Date Admitted:</label>
                    {{ form.check_in_date }}
                </div>

                <div class="form-group">
                    <label for="">Period Admitted:</label>
                    {{ form.check_in_period }}
                </div>

                <div class="form-group">
                    <label for="">Date Discharged:</label>
                    {{ form.check_out_date }}
                </div>

                <div class="form-group">
                    <label for="">Period Discharged:</label>
                    {{ form.check_out_period }}
                </div>

                <div class="form-group">
                    <label for="">Patient:</label>
                    {{ form.patient }}
                </div>

                <div class="form-group">
                    <label for="">Assigned Doctor:</label>
                    {{ form.assigned_doctor }}
                </div>

                <div class="form-group">
                    <input type="submit" value="Submit" class="btn btn-success col-4 float-right">
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}